### PR TITLE
Fix program name in diagram

### PR DESCRIPTION
**Pull request by mikemaccana**
SOL is transferred with the system program not the token program

### CODE REVIEW

**Comment by Woody4618** [comment]
The function signature of systemProgram.transfer is from, to, lamports 
https://docs.rs/solana-program/latest/solana_program/system_instruction/fn.transfer.html

**Comment by mikemaccana** [comment]
@Woody4618 fixed!

**Comment by Woody4618** [comment]
The amount in the function is still wrong. Its lamports, not sol. 
https://docs.rs/solana-program/latest/solana_program/system_instruction/fn.transfer.html

**Review by Woody4618 — APPROVED** [review]

**Comment by mikemaccana** [comment]
Done! @Woody4618

**Comment by Woody4618** [comment]
Nice. 👍  Looks like you still need @nickfrosty s review for merge.

**Review by nickfrosty — APPROVED** [review]

**Pull request merged**
