### PR TITLE
fix and improve program-configuration.md & program-architecture.md

### PR DESCRIPTION
**Pull request by wuuer**
#### program-configuration.md
The error message is not expected in the section "Run the existing test" section.
The "--skip-deploy" option for the test command `anchor test` is required as the deploy function is found in the typescript. `anchor test`  will deploy the program with program_data's upgrade_authority_address set to system program (11111111111111111111111111111111), which results in an error while running the test case "Initialize Admin config should be successfully" . Deploying the program by the typescript function `deploy` will set the program_data's upgrade_authority_address to the wallet used.
The course has included the challenging content.
#### program-architecture.md
[stack] and [heap] docs links are invalid.
[reallocate the account] link is invalid.
[clockwork] link is invalid.
The [advanced-program-architecture] repo including the latest version update is found.

#### program-configuration.md
Update the correct error message in the section "Run the existing test".
Add “--skip-deploy” to the test command.
Delete an unnecessary setup in the section "Adding a `local-testing` feature".
Remove the challenge section.

**Also, I made a [PR](https://github.com/Unboxed-Software/solana-admin-instructions/pull/1) for [solana-admin-instructions](https://github.com/Unboxed-Software/solana-admin-instructions/tree/starter) starter branch and a [PR](https://github.com/Unboxed-Software/solana-admin-instructions/pull/2) for [solana-admin-instructions](https://github.com/Unboxed-Software/solana-admin-instructions/tree/solution) solution branch
which must be synced with this PR.**

#### program-architecture.md
Update [stack] and [heap] docs links.
Update [reallocate the account] link.
Update [clockwork] link.
Update [advanced-program-architecture] repo link.

### CODE REVIEW

**Comment by mikemaccana** [comment]
Just a note to myself that this PR covers the same files as https://github.com/solana-foundation/developer-content/pull/372

**Comment by wuuer** [comment]
> Just a note to myself that this PR covers the same files as #372. See [#372 (comment)](https://github.com/solana-foundation/developer-content/pull/372#issuecomment-2329922343)

see
https://github.com/solana-foundation/developer-content/pull/372#issuecomment-2330435420

**Review by mikemaccana — CHANGES_REQUESTED** [review]
> This PR(https://github.com/solana-foundation/developer-content/pull/423) is for program-optimization course content.|

Check the Files tab of this PR #423. There are a bunch of changes in program-security course.

> This PR(https://github.com/solana-foundation/developer-content/pull/372) is for program-security course content.

Remove the program-security changes from this PR.

Then please find and remove any other overlaps - thanks!

**Comment by wuuer** [comment]
> > This PR(#423) is for program-optimization course content.|
> 
> Check the Files tab of this PR #423. There are a bunch of changes in program-security course.
> 
> > This PR(#372) is for program-security course content.
> 
> Remove the program-security changes from this PR.
> 
> Then please find and remove any other overlaps - thanks!

@mikemaccana Got it.

**Pull request closed without merging**
