### PR TITLE
Game dev content

### PR DESCRIPTION
**Pull request by Woody4618**
### Summary of Changes

I moved all content from cookbook into guides and brought them to the newest state, fixed the links and images and added a new guide about dynamic meta data NFTs. 

The Solana games kit is now also a guide and all old and broken links were removed.

### CODE REVIEW

**Comment by Woody4618** [comment]
Thank you very much @nickfrosty for all these fixes!

**Comment by jacobcreech** [comment]
@Woody4618 can we get each guide into a separate PR? That would be a lot easier to review by miles

**Review by mikemaccana — CHANGES_REQUESTED** [review]
All good. Just lots of small English fixes and a couple of capitalization bits needed.

**Comment by Woody4618** [comment]
> @Woody4618 can we get each guide into a separate PR? That would be a lot easier to review by miles

Mike and Nick went through everything already. Maybe not necessary anymore?

**Comment by nickfrosty** [comment]
@Woody4618 don't worry about splitting this into multiple PRs since the review is already in progress. I am about half way through it

**Review by nickfrosty — APPROVED** [review]
Thanks for all the work on this @Woody4618!

**Comment by Woody4618** [comment]
Thanks for the biiig review 🤗

**Pull request merged**
