### PR TITLE
Add secret key creation/loading guide

### PR DESCRIPTION
**Pull request by AlmostEfficient**
**Problem**
There's no guide that talks about what the different types of secret key formats on Solana are, what they're used for, and how you can generate/load them.

**Solution**
This guide:
- Explains the 4 main types of key material: Mnemonic, byte array, base58, hex
- Shows generation of each type
- Shows loading/reading of each type

Open to suggestions/further reading on secure practices as I don't have much there, leaving that to the reader.

### CODE REVIEW

**Comment by mikemaccana** [comment]
@AlmostEfficient would you like to contribute to @solana-developers/helpers? Currently https://github.com/solana-developers/helpers?tab=readme-ov-file#getkeypairfromfilefilename loads byte array and base58 versions, it may be useful to add support for mnemonics too. The intention is to be strict in how we save things, so we use byte array to save in, consistent with Solana CLI. 

Bigger picture, the idea is to avoid boilerplate code and ensure there's a single place with tested code to handle common tasks like these.

**Comment by AlmostEfficient** [comment]
Great idea, will add mnemonics support!

**Comment by mikemaccana** [comment]
@AlmostEfficient "force-pushed the main branch from eee64a3 to 734fdc3" this seems concerning!

**Comment by AlmostEfficient** [comment]
🤦

My bad, forgot this was still open and nuked main when working on a fix for the full stack guide. Will reopen later.

**Pull request closed without merging**
