### PR TITLE
update/token program frontend update

### PR DESCRIPTION
**Pull request by Tarunrao0**
This PR is intended to reference PRs made in unbox-software related to the token-program lesson 

# Problems
- older version of nextjs `12.1.2`
- `src` directory structure
- WalletMultiButton in AppBar  wasnt functional in latest version of nextjs

# Summary

- Updated both `starter` code and `solution` code to use the `create-solana-dapp` CLI

#### References to the PRs in Unboxed-Software :  [#5](https://github.com/Unboxed-Software/solana-token-frontend/pull/5)  ,  [#6](https://github.com/Unboxed-Software/solana-token-frontend/pull/6)

### CODE REVIEW

**Comment by Tarunrao0** [comment]
@mikemaccana could you please check this PR out. ty

**Comment by mikemaccana** [comment]
Thanks @Tarunrao0. As mentioned in the Superteam proposal, can you use `create-solana-dapp` to update these repos? Your existing code should be reusable within that.

**Review by mikemaccana — CHANGES_REQUESTED** [review]
See comment above re: create-solana-dapp.

**Comment by Tarunrao0** [comment]
> Thanks @Tarunrao0. As mentioned in the Superteam proposal, can you use `create-solana-dapp` to update these repos? Your existing code should be reusable within that.

@mikemaccana Thank you for the response, I have updated both the starter and solution codes to be built with `create-solana-dapp`.

**Comment by mikemaccana** [comment]
Thanks @Tarunrao0 !  https://github.com/Unboxed-Software/solana-token-frontend/pull/5 is merged, can you fix the conflicts on https://github.com/Unboxed-Software/solana-token-frontend/pull/6 ?

Pardon the wait, we had a 24-person class, then Rustconf then Breakpoint. After we get the PRs updated I will move the repo to solana-developers, we will change the URL here, and we can merge this.

**Review by mikemaccana — COMMENTED** [review]
Thanks @Tarunrao0 !  https://github.com/Unboxed-Software/solana-token-frontend/pull/5 is merged, can you fix the conflicts on https://github.com/Unboxed-Software/solana-token-frontend/pull/6 ?

Pardon the wait, we had a 24-person class, then Rustconf then Breakpoint. After we get the PRs updated I will move the repo to solana-developers, we will change the URL here, and we can merge this.

**Review by mikemaccana — CHANGES_REQUESTED** [review]
Thanks @Tarunrao0 !  https://github.com/Unboxed-Software/solana-token-frontend/pull/5 is merged, can you fix the conflicts on https://github.com/Unboxed-Software/solana-token-frontend/pull/6 ?

Pardon the wait, we had a 24-person class, then Rustconf then Breakpoint. After we get the PRs updated I will move the repo to solana-developers, we will change the URL here, and we can merge this.

**Review by mikemaccana — CHANGES_REQUESTED** [review]
Just a note to look at https://github.com/Unboxed-Software/solana-token-frontend/pull/6

**Pull request closed without merging**
