### PR TITLE
Update docs for higher accuracy and quality of information

### PR DESCRIPTION
**Pull request by intls**
### Problem

Typos and grammar and spelling errors around docs files.

### Summary of Changes

Fixed critical inaccuracies and enhanced readability of the documentation to ensure better understanding by developers.

Fixes #

### CODE REVIEW

**Review by nickfrosty — CHANGES_REQUESTED** [review]
Thanks for fixing all these grammar issues. Can you run the prettier formatting to satisfy the prettier action check?

**Review by nickfrosty — APPROVED** [review]

**Comment by intls** [comment]
> Thanks for fixing all these grammar issues. Can you run the prettier formatting to satisfy the prettier action check?

Thanks!Sure I will make it asap!

**Comment by intls** [comment]
> Thanks for fixing all these grammar issues. Can you run the prettier formatting to satisfy the prettier action check?

@nickfrosty HEY!! Prettier has been applied to the specified files, but no changes were necessary as they were already correctly formatted. Let me know if there's anything else I should address!

**Comment by nickfrosty** [comment]
Thanks! I went ahead and ran the prettier myself and the PR was already merged

**Pull request merged**
