### PR TITLE
feat: add the-complete-guide-to-full-stack-solana-development

### PR DESCRIPTION
**Pull request by ImmuneFOMO**
add guide for full stack solana development with React, Anchor, Rust, and Phantom

### CODE REVIEW

**Comment by ImmuneFOMO** [comment]
add guide for full stack solana development with React, Anchor, Rust, and Phantom

**Comment by nickfrosty** [comment]
Thanks for writing up this developer guide during the Scribes hackathon! It is pretty great one. Unfortunately, since we can only publish one "Solana full stack development" guide on the Solana website and it will be a different one. So I will close this PR.

I see you also published your guide to medium, which is amazing! I will share the link for your medium post here for anyone else that sees this too:
https://medium.com/@Anatolii_Zhadan/the-complete-guide-to-full-stack-solana-development-with-react-anchor-rust-and-phantom-18a1e1bdbb3b

**Comment by nickfrosty** [comment]
If you are interested, I would love for you to write a guide on testing programs within rust?

**Comment by ImmuneFOMO** [comment]
Yes I can try that, we can liaise somewhere and detail how you would like to see it, well or you can just describe it here

**Comment by nickfrosty** [comment]
Send me a DM on twitter https://twitter.com/nickfrosty

**Comment by ImmuneFOMO** [comment]
check please twitter dm

**Pull request closed without merging**
