### PR TITLE
Ask people to run a grammar check prior to PR, and to use US English

### PR DESCRIPTION
**Pull request by mikemaccana**
IIRC you suggested this yesterday, it was a good idea.

### CODE REVIEW

**Comment by mikemaccana** [comment]
lol `Code style issues found in the above file. Run Prettier to fix.`.

**Comment by mikemaccana** [comment]
@nickfrosty can we disable prettier (with a view to having it be run by github actions in future) or do you want us to pull anything we edit on github down to our local machines, run prettier, and reupload?

**Comment by nickfrosty** [comment]
@mikemaccana no we will not disable it: https://github.com/solana-foundation/developer-content/blob/main/CONTRIBUTING.md#prettier

**Review by nickfrosty — CHANGES_REQUESTED** [review]
I like the addition, but let's move this further to the top of the document. Since this repo is basically all written content, it makes more sense to make this more of a focus.

Maybe just above content guidelines? Also: run prettier :)

**Comment by jacobcreech** [comment]
Can we just recommend to use the grammarly app for checking english instead of a vscode extension? Not everyone uses vscode but everyone uses a browser.

**Comment by mikemaccana** [comment]
> Can we just recommend to use the grammarly app for checking english instead of a vscode extension? Not everyone uses vscode but everyone uses a browser.

> I like the addition, but let's move this further to the top of the document. Since this repo is basically all written content, it makes more sense to make this more of a focus.

Yep. I'll merge this into my other PR, one moment...

> Also: run prettier :)

The reason I asked you about fixing the tests is the previous conversation we'd had about how the github editor doesn't run prettier, and having the test fail stops people being able to quickly fix anything using the github editor - exactly like it has here! As we discussed the proper thing to do is have github actions run prettier and do a commit, which I think you were planning on getting working.

**Comment by mikemaccana** [comment]
Merged into https://github.com/solana-foundation/developer-content/pull/201

**Pull request closed without merging**
