### PR TITLE
serialialize-instruction-data-frontend more changes (was refactor(): replace deprecated findProgramAddress with findProgramAddressSync)

### PR DESCRIPTION
**Pull request by EmekaManuel**
fix: replace deprecated findProgramAddress with findProgramAddressSync

### Problem
The method 'web3.PublicKey.findProgramAddress' is deprecated and may lead to compatibility issues.

### Summary of Changes
- Replaced the deprecated `findProgramAddress` method with the recommended `findProgramAddressSync` method for more reliable and up-to-date usage.

### CODE REVIEW

**Comment by mikemaccana** [comment]
Thanks @EmekaManuel ! This is a good start, but there's still a little more you can do here - including use `await` instead of `.then()`, linting the code, and using full names instead `tx` - see https://github.com/solana-foundation/developer-content/blob/main/CONTRIBUTING.md. Can you also make the code just import `Connection` etc from web3, rather than importing all of web3? It's a little more efficient and also stops people from having to type `web3.` all the time.

I saw your comment on Superteam Earn:

> I rebuilt the buggy and outdated movie review app used to explain serialization, deserialization, pagination and sorting using the latest version of technology: Nextjs, typescript, tailwind, and web3js. The repo is here : https://github.com/EmekaManuel/Solana-Movie-Review-Frontend

Excellent! Can you please use https://github.com/solana-developers/create-solana-dapp to do this (as mentioned in the bounty)? It uses the same stack, but we want to make sure we're using the same tools to kickstart Solana frontend apps. 

After that we should be able to get this PR merged.

**Comment by EmekaManuel** [comment]
hello Mike, I have made the necessary changes : 
- Imported specific modules instead of the entire package from web3js
- Replaced .then() with await for better readability and async handling.
- Applied linting to maintain code consistency and clarity.
- Replaced abbreviations like tx  with more descriptive variable names for better code readability.
- Enhanced error handling using trycatch.

**Comment by mikemaccana** [comment]
Move this work into #369. We don't want to split a person's updates over multiple PRs and we need to keep the conversation in one place.

In #368 I previously asked to add the images to that PR (ie, #368).

**Review by mikemaccana — CHANGES_REQUESTED** [review]
Move into your other PR.

**Comment by EmekaManuel** [comment]
> Move into your other PR.

Just merged into #369. Please note that these PR's focus on two courses which are `update-program-state-management` and the `serialize-instruction-data-frontend`

**Comment by mikemaccana** [comment]
Closing as will review in #369

**Pull request closed without merging**
