### PR TITLE
Update how-to-create-a-token.md

### PR DESCRIPTION
**Pull request by tracy-codes**
Correct Shadow Drive details

### Problem

The `Details` section for `Shadow Drive` state there was an issue without any information. At the time of creating this article there was a stability issue due to the priority fee rush at the beginning of the memecoin craze. This has since been resolved.

### Summary of Changes

Corrected the `Details` section for `Shadow Drive`.

Fixes #

### CODE REVIEW

**Comment by Woody4618** [comment]
Hey, happy to take that part out since its without context. I am still not able to create new storage account though, no matter the input it always sais: 

image

Looks like the error in the console is CORS policy related maybe: 

```
Access to fetch at 'https://sentry.genesysgo.net/api/3/envelope/?sentry_key=4710abebb22f7a54fc481f1f7cb70d6a&sentry_version=7&sentry_client=sentry.javascript.react%2F7.77.0' from origin 'https://portal.shdwdrive.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
sentry.genesysgo.net/api/3/envelope/?sentry_key=4710abebb22f7a54fc481f1f7cb70d6a&sentry_version=7&sentry_client=sentry.javascript.react%2F7.77.0:1 
        
        
       POST https://sentry.genesysgo.net/api/3/envelope/?sentry_key=4710abebb22f7a54fc481f1f7cb70d6a&sentry_version=7&sentry_client=sentry.javascript.react%2F7.77.0 net::ERR_FAILED 404 (Not Found)

I also wrote support and didnt get a reply so we thought that part wasnt maintained anymore maybe and didnt want people to get stuck. 
```

**Comment by tracy-codes** [comment]
Ahh interesting, I didn't see that reported in support. We'll take a look at this. The 404s in the console are for sentry which is just a metrics collection service which has since moved to a different domain.

I'll follow up once we've taken a look into your specific issue though!

**Comment by tracy-codes** [comment]
> Hey, happy to take that part out since its without context. I am still not able to create new storage account though, no matter the input it always sais:
> image

What was your input to get this error? Our team just tested creating new storage accounts through our example portal and they all didn't encounter this error when creating them. Are you actually putting something into the input or just leaving it blank / default / not modifying the input for the storage account size?

Along with that, what browser are you using?

**Comment by tracy-codes** [comment]
Following up on this. Whats needed to get this merged?

**Review by Woody4618 — APPROVED** [review]

**Comment by Woody4618** [comment]
Seems to all work now. 
@nickfrosty could you merge this pls

**Review by jacobcreech — APPROVED** [review]

**Pull request merged**
