### PR TITLE
Update verifiable randomness functions.md

### PR DESCRIPTION
**Pull request by adpthegreat**
### Summary of Changes

- Updated link to starter code from https://github.com/Unboxed/-Software/michael-burry-escrow
 To https://github.com/solana-developers/burry-escrow

- Renamed escrowState to Escrow in the ts tests 

- Renamed VrfClientState to VrfClient

- Corrected solUsedSwitchBoardFeed to solUsdSwitchBoardFeed 

- Renamed escrow_amt to escrow_amount

- Renamed all variables with "ix" to Instruction

- Renamed tx to transaction in the burry-escrow.ts

 Used anchors INITSPACE ,instead of std::mem::size also replaced the magic number 8 with an anchor discriminator variable 

- Fixed some grammar errors 

- Removed unnecessary awaits in test

- Changed the type for unlock_price from f64 to u64 

- edited subheadings from #### to ### for consistency 

-Renamed VRF_STATE_SEED TO VRF_STATE

- Updated assertions comparing numbers in tests to use .eq() method in place of === 

- changed anchor.BN to BN

- Wrapped solPrice with BN 

- renamed e to error for more clarity

- Ran code to make sure tests work accordingly 

- Created PRs in https://github.com/solana-developers/burry-escrow to add branches vrf and vrf-challenge-solution as well as fixes to burry escrow 
Screenshot 2024-09-12 at 05 30 12

### CODE REVIEW

**Comment by adpthegreat** [comment]
This is my second PR here [update-compressed-nfts](https://github.com/solana-foundation/developer-content/pull/523)

**Comment by adpthegreat** [comment]
@mikemaccana any update on this ?

**Comment by mikemaccana** [comment]
Thanks for this @adpthegreat ! While you didn't win the prize for this lesson, we'd still love to get some of these fixes in - could you please rebase on top of current `main`?

**Review by mikemaccana — CHANGES_REQUESTED** [review]
Thanks for this @adpthegreat ! While you didn't win the prize for this lesson, we'd still love to get some of these fixes in - could you please rebase on top of current `main`?

**Comment by adpthegreat** [comment]
yeah I've done that now

**Pull request closed without merging**
